[en]
    label  = "English"
    title  = "Bothbest Bamboo Flooring"
    weight = 1

    [en.params.sidebar]
        subtitle = "China bamboo flooring supplier since 2001"

[zh]
    label  = "简体中文"
    title  = "Bothbest Bamboo Flooring"
    weight = 2

    [zh.params.sidebar]
        subtitle = "China bamboo flooring supplier since 2001"

[zh-hant-tw]
    label  = "正體中文"
    title  = "Bothbest Bamboo Flooring"
    weight = 3

    [zh-hant-tw.params.sidebar]
        subtitle = "China bamboo flooring supplier since 2001"

[ja]
    label  = "日本語"
    title  = "Bothbest Bamboo Flooring"
    weight = 4

    [ja.params.sidebar]
        subtitle = "China bamboo flooring supplier since 2001"
